# Generated by Django 3.2.6 on 2021-08-26 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('m', 'male'), ('f', 'female')], default='m', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='masters',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_column='Full name', max_length=100),
        ),
    ]
