# Generated by Django 3.2.6 on 2021-08-26 17:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210826_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='Updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
