# Generated by Django 3.2.6 on 2021-08-30 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='dept',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.department'),
            preserve_default=False,
        ),
    ]
