# Generated by Django 3.2.6 on 2021-09-05 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_department_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
